kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secert: docker_password
    repo: swarm101/rproxy
    auto_tag: true

