version: "3.6"

services:
    rproxy:
        image: rproxy
        deploy:
            placement:
                constraints: 
                - node.role == manager
        ports:
        - 80:80
        - 443:443
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - data:/data
        networks:
        - rproxy

volumes:
    data:

networks:
    rproxy:
        name: "rproxy"
        attachable: true
